
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.lexical.analyzer;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DISPLAY = 22;
  public static final int ENDDEF = 9;
  public static final int PROGRAMSECTION = 26;
  public static final int OP_MAYOR = 38;
  public static final int OUTPUT = 28;
  public static final int PARENTESIS_CIERRA = 49;
  public static final int FIN_INSTRUCCION = 30;
  public static final int TIPO_REAL = 4;
  public static final int OTHER = 23;
  public static final int CASE = 11;
  public static final int DOS_PUNTOS = 50;
  public static final int TIPO_STRING = 5;
  public static final int OP_MULTIPLICACION = 34;
  public static final int FIN = 3;
  public static final int FOR = 15;
  public static final int AND = 42;
  public static final int BLOQUE_CIERRA = 45;
  public static final int OR = 43;
  public static final int CORCHETE_CIERRA = 47;
  public static final int ENDFOR = 16;
  public static final int IF = 17;
  public static final int ID = 20;
  public static final int ENDWHILE = 21;
  public static final int EOF = 0;
  public static final int OP_DIVISION = 35;
  public static final int error = 1;
  public static final int COMA = 29;
  public static final int OP_RESTA = 33;
  public static final int BREAK = 13;
  public static final int TIPO_INT = 6;
  public static final int OP_ASIGNACION = 31;
  public static final int OP_DISTINTO = 37;
  public static final int OP_MAYOR_IGUAL = 40;
  public static final int CORCHETE_ABRE = 46;
  public static final int ENDIF = 18;
  public static final int ELSE = 10;
  public static final int OP_IGUAL = 36;
  public static final int WHILE = 19;
  public static final int OP_MENOR_IGUAL = 41;
  public static final int CONST_STRING = 51;
  public static final int LONG = 7;
  public static final int INICIO = 2;
  public static final int DEFVAR = 8;
  public static final int OP_SUMA = 32;
  public static final int CONST_REAL = 53;
  public static final int ENDDECLARESECTION = 25;
  public static final int PARENTESIS_ABRE = 48;
  public static final int ENDCASE = 14;
  public static final int DO = 12;
  public static final int CONST_INT = 52;
  public static final int BLOQUE_ABRE = 44;
  public static final int OP_MENOR = 39;
  public static final int ENDPROGRAMSECTION = 27;
  public static final int DECLARESECTION = 24;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INICIO",
  "FIN",
  "TIPO_REAL",
  "TIPO_STRING",
  "TIPO_INT",
  "LONG",
  "DEFVAR",
  "ENDDEF",
  "ELSE",
  "CASE",
  "DO",
  "BREAK",
  "ENDCASE",
  "FOR",
  "ENDFOR",
  "IF",
  "ENDIF",
  "WHILE",
  "ID",
  "ENDWHILE",
  "DISPLAY",
  "OTHER",
  "DECLARESECTION",
  "ENDDECLARESECTION",
  "PROGRAMSECTION",
  "ENDPROGRAMSECTION",
  "OUTPUT",
  "COMA",
  "FIN_INSTRUCCION",
  "OP_ASIGNACION",
  "OP_SUMA",
  "OP_RESTA",
  "OP_MULTIPLICACION",
  "OP_DIVISION",
  "OP_IGUAL",
  "OP_DISTINTO",
  "OP_MAYOR",
  "OP_MENOR",
  "OP_MAYOR_IGUAL",
  "OP_MENOR_IGUAL",
  "AND",
  "OR",
  "BLOQUE_ABRE",
  "BLOQUE_CIERRA",
  "CORCHETE_ABRE",
  "CORCHETE_CIERRA",
  "PARENTESIS_ABRE",
  "PARENTESIS_CIERRA",
  "DOS_PUNTOS",
  "CONST_STRING",
  "CONST_INT",
  "CONST_REAL"
  };
}

