package com.lexical.analyzer;

public enum Tokens {
	LONG, DEFVAR, COMA, DOS_PUNTOS, ENDDEF, ELSE, IF, WHILE, WRITE, FIN_INSTRUCCION, ID, CONST_REAL, CONST_INT, CONST_STRING, OP_ASIGNACION, OP_IGUAL, OP_SUMA, OP_RESTA, OP_MULTIPLICACION, OP_DIVISION, OP_DISTINTO, OP_MAYOR_IGUAL, OP_MENOR_IGUAL, OP_MAYOR, OP_MENOR, BLOQUE_ABRE, BLOQUE_CIERRA, CORCHETE_ABRE, CORCHETE_CIERRA, PARENTESIS_ABRE, PARENTESIS_CIERRA, DOS_PUNTO, ERROR
}
